// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: claudeplane/v1/agent.proto

package claudeplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MachineId        string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	MaxSessions      int32                  `protobuf:"varint,2,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	Resources        *ResourceInfo          `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	ExistingSessions []*SessionState        `protobuf:"bytes,4,rep,name=existing_sessions,json=existingSessions,proto3" json:"existing_sessions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *RegisterRequest) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *RegisterRequest) GetResources() *ResourceInfo {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *RegisterRequest) GetExistingSessions() []*SessionState {
	if x != nil {
		return x.ExistingSessions
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	ServerVersion string                 `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *RegisterResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

type ResourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuCores      int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskFreeBytes int64                  `protobuf:"varint,3,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ResourceInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceInfo) GetDiskFreeBytes() int64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

type SessionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SessionState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionState) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SessionState) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *SessionState) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

type ServerCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ServerCommand_CreateSession
	//	*ServerCommand_AttachSession
	//	*ServerCommand_DetachSession
	//	*ServerCommand_KillSession
	//	*ServerCommand_ResizeTerminal
	//	*ServerCommand_InputData
	//	*ServerCommand_RequestScrollback
	Command       isServerCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ServerCommand) GetCommand() isServerCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ServerCommand) GetCreateSession() *CreateSessionCmd {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_CreateSession); ok {
			return x.CreateSession
		}
	}
	return nil
}

func (x *ServerCommand) GetAttachSession() *AttachSessionCmd {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_AttachSession); ok {
			return x.AttachSession
		}
	}
	return nil
}

func (x *ServerCommand) GetDetachSession() *DetachSessionCmd {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_DetachSession); ok {
			return x.DetachSession
		}
	}
	return nil
}

func (x *ServerCommand) GetKillSession() *KillSessionCmd {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_KillSession); ok {
			return x.KillSession
		}
	}
	return nil
}

func (x *ServerCommand) GetResizeTerminal() *ResizeTerminalCmd {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_ResizeTerminal); ok {
			return x.ResizeTerminal
		}
	}
	return nil
}

func (x *ServerCommand) GetInputData() *InputDataCmd {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_InputData); ok {
			return x.InputData
		}
	}
	return nil
}

func (x *ServerCommand) GetRequestScrollback() *RequestScrollbackCmd {
	if x != nil {
		if x, ok := x.Command.(*ServerCommand_RequestScrollback); ok {
			return x.RequestScrollback
		}
	}
	return nil
}

type isServerCommand_Command interface {
	isServerCommand_Command()
}

type ServerCommand_CreateSession struct {
	CreateSession *CreateSessionCmd `protobuf:"bytes,1,opt,name=create_session,json=createSession,proto3,oneof"`
}

type ServerCommand_AttachSession struct {
	AttachSession *AttachSessionCmd `protobuf:"bytes,2,opt,name=attach_session,json=attachSession,proto3,oneof"`
}

type ServerCommand_DetachSession struct {
	DetachSession *DetachSessionCmd `protobuf:"bytes,3,opt,name=detach_session,json=detachSession,proto3,oneof"`
}

type ServerCommand_KillSession struct {
	KillSession *KillSessionCmd `protobuf:"bytes,4,opt,name=kill_session,json=killSession,proto3,oneof"`
}

type ServerCommand_ResizeTerminal struct {
	ResizeTerminal *ResizeTerminalCmd `protobuf:"bytes,5,opt,name=resize_terminal,json=resizeTerminal,proto3,oneof"`
}

type ServerCommand_InputData struct {
	InputData *InputDataCmd `protobuf:"bytes,6,opt,name=input_data,json=inputData,proto3,oneof"`
}

type ServerCommand_RequestScrollback struct {
	RequestScrollback *RequestScrollbackCmd `protobuf:"bytes,7,opt,name=request_scrollback,json=requestScrollback,proto3,oneof"`
}

func (*ServerCommand_CreateSession) isServerCommand_Command() {}

func (*ServerCommand_AttachSession) isServerCommand_Command() {}

func (*ServerCommand_DetachSession) isServerCommand_Command() {}

func (*ServerCommand_KillSession) isServerCommand_Command() {}

func (*ServerCommand_ResizeTerminal) isServerCommand_Command() {}

func (*ServerCommand_InputData) isServerCommand_Command() {}

func (*ServerCommand_RequestScrollback) isServerCommand_Command() {}

type CreateSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	InitialPrompt string                 `protobuf:"bytes,6,opt,name=initial_prompt,json=initialPrompt,proto3" json:"initial_prompt,omitempty"`
	TerminalSize  *TerminalSize          `protobuf:"bytes,7,opt,name=terminal_size,json=terminalSize,proto3" json:"terminal_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionCmd) Reset() {
	*x = CreateSessionCmd{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionCmd) ProtoMessage() {}

func (x *CreateSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionCmd.ProtoReflect.Descriptor instead.
func (*CreateSessionCmd) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionCmd) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CreateSessionCmd) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *CreateSessionCmd) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateSessionCmd) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CreateSessionCmd) GetInitialPrompt() string {
	if x != nil {
		return x.InitialPrompt
	}
	return ""
}

func (x *CreateSessionCmd) GetTerminalSize() *TerminalSize {
	if x != nil {
		return x.TerminalSize
	}
	return nil
}

type AttachSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachSessionCmd) Reset() {
	*x = AttachSessionCmd{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachSessionCmd) ProtoMessage() {}

func (x *AttachSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachSessionCmd.ProtoReflect.Descriptor instead.
func (*AttachSessionCmd) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AttachSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DetachSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachSessionCmd) Reset() {
	*x = DetachSessionCmd{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachSessionCmd) ProtoMessage() {}

func (x *DetachSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachSessionCmd.ProtoReflect.Descriptor instead.
func (*DetachSessionCmd) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DetachSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KillSessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionCmd) Reset() {
	*x = KillSessionCmd{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionCmd) ProtoMessage() {}

func (x *KillSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionCmd.ProtoReflect.Descriptor instead.
func (*KillSessionCmd) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *KillSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KillSessionCmd) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type ResizeTerminalCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Size          *TerminalSize          `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTerminalCmd) Reset() {
	*x = ResizeTerminalCmd{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTerminalCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTerminalCmd) ProtoMessage() {}

func (x *ResizeTerminalCmd) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTerminalCmd.ProtoReflect.Descriptor instead.
func (*ResizeTerminalCmd) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ResizeTerminalCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResizeTerminalCmd) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

type InputDataCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputDataCmd) Reset() {
	*x = InputDataCmd{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputDataCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputDataCmd) ProtoMessage() {}

func (x *InputDataCmd) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputDataCmd.ProtoReflect.Descriptor instead.
func (*InputDataCmd) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *InputDataCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InputDataCmd) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestScrollbackCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestScrollbackCmd) Reset() {
	*x = RequestScrollbackCmd{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestScrollbackCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestScrollbackCmd) ProtoMessage() {}

func (x *RequestScrollbackCmd) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestScrollbackCmd.ProtoReflect.Descriptor instead.
func (*RequestScrollbackCmd) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RequestScrollbackCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TerminalSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *TerminalSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type AgentEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*AgentEvent_SessionOutput
	//	*AgentEvent_SessionStatus
	//	*AgentEvent_Health
	//	*AgentEvent_ScrollbackChunk
	//	*AgentEvent_SessionExit
	Event         isAgentEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AgentEvent) GetEvent() isAgentEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentEvent) GetSessionOutput() *SessionOutputEvent {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_SessionOutput); ok {
			return x.SessionOutput
		}
	}
	return nil
}

func (x *AgentEvent) GetSessionStatus() *SessionStatusEvent {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_SessionStatus); ok {
			return x.SessionStatus
		}
	}
	return nil
}

func (x *AgentEvent) GetHealth() *HealthEvent {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *AgentEvent) GetScrollbackChunk() *ScrollbackChunkEvent {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_ScrollbackChunk); ok {
			return x.ScrollbackChunk
		}
	}
	return nil
}

func (x *AgentEvent) GetSessionExit() *SessionExitEvent {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_SessionExit); ok {
			return x.SessionExit
		}
	}
	return nil
}

type isAgentEvent_Event interface {
	isAgentEvent_Event()
}

type AgentEvent_SessionOutput struct {
	SessionOutput *SessionOutputEvent `protobuf:"bytes,1,opt,name=session_output,json=sessionOutput,proto3,oneof"`
}

type AgentEvent_SessionStatus struct {
	SessionStatus *SessionStatusEvent `protobuf:"bytes,2,opt,name=session_status,json=sessionStatus,proto3,oneof"`
}

type AgentEvent_Health struct {
	Health *HealthEvent `protobuf:"bytes,3,opt,name=health,proto3,oneof"`
}

type AgentEvent_ScrollbackChunk struct {
	ScrollbackChunk *ScrollbackChunkEvent `protobuf:"bytes,4,opt,name=scrollback_chunk,json=scrollbackChunk,proto3,oneof"`
}

type AgentEvent_SessionExit struct {
	SessionExit *SessionExitEvent `protobuf:"bytes,5,opt,name=session_exit,json=sessionExit,proto3,oneof"`
}

func (*AgentEvent_SessionOutput) isAgentEvent_Event() {}

func (*AgentEvent_SessionStatus) isAgentEvent_Event() {}

func (*AgentEvent_Health) isAgentEvent_Event() {}

func (*AgentEvent_ScrollbackChunk) isAgentEvent_Event() {}

func (*AgentEvent_SessionExit) isAgentEvent_Event() {}

type SessionOutputEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOutputEvent) Reset() {
	*x = SessionOutputEvent{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOutputEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOutputEvent) ProtoMessage() {}

func (x *SessionOutputEvent) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOutputEvent.ProtoReflect.Descriptor instead.
func (*SessionOutputEvent) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *SessionOutputEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionOutputEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SessionOutputEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SessionStatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusEvent) Reset() {
	*x = SessionStatusEvent{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusEvent) ProtoMessage() {}

func (x *SessionStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusEvent.ProtoReflect.Descriptor instead.
func (*SessionStatusEvent) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SessionStatusEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStatusEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SessionExitEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExitCode        int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExitedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=exited_at,json=exitedAt,proto3" json:"exited_at,omitempty"`
	ScrollbackBytes int64                  `protobuf:"varint,4,opt,name=scrollback_bytes,json=scrollbackBytes,proto3" json:"scrollback_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionExitEvent) Reset() {
	*x = SessionExitEvent{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExitEvent) ProtoMessage() {}

func (x *SessionExitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExitEvent.ProtoReflect.Descriptor instead.
func (*SessionExitEvent) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SessionExitEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionExitEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SessionExitEvent) GetExitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitedAt
	}
	return nil
}

func (x *SessionExitEvent) GetScrollbackBytes() int64 {
	if x != nil {
		return x.ScrollbackBytes
	}
	return 0
}

type HealthEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent float32                `protobuf:"fixed32,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes int64                  `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	DiskFreeBytes   int64                  `protobuf:"varint,3,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	ActiveSessions  int32                  `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	MaxSessions     int32                  `protobuf:"varint,5,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthEvent) Reset() {
	*x = HealthEvent{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthEvent) ProtoMessage() {}

func (x *HealthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthEvent.ProtoReflect.Descriptor instead.
func (*HealthEvent) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *HealthEvent) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *HealthEvent) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *HealthEvent) GetDiskFreeBytes() int64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

func (x *HealthEvent) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *HealthEvent) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

type ScrollbackChunkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollbackChunkEvent) Reset() {
	*x = ScrollbackChunkEvent{}
	mi := &file_claudeplane_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollbackChunkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollbackChunkEvent) ProtoMessage() {}

func (x *ScrollbackChunkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_claudeplane_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollbackChunkEvent.ProtoReflect.Descriptor instead.
func (*ScrollbackChunkEvent) Descriptor() ([]byte, []int) {
	return file_claudeplane_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ScrollbackChunkEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScrollbackChunkEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScrollbackChunkEvent) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *ScrollbackChunkEvent) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ScrollbackChunkEvent) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_claudeplane_v1_agent_proto protoreflect.FileDescriptor

const file_claudeplane_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aclaudeplane/v1/agent.proto\x12\x0eclaudeplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12!\n" +
	"\fmax_sessions\x18\x02 \x01(\x05R\vmaxSessions\x12:\n" +
	"\tresources\x18\x03 \x01(\v2\x1c.claudeplane.v1.ResourceInfoR\tresources\x12I\n" +
	"\x11existing_sessions\x18\x04 \x03(\v2\x1c.claudeplane.v1.SessionStateR\x10existingSessions\"z\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\"v\n" +
	"\fResourceInfo\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12&\n" +
	"\x0fdisk_free_bytes\x18\x03 \x01(\x03R\rdiskFreeBytes\"\xf9\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendedAt\x88\x01\x01\x12 \n" +
	"\texit_code\x18\x05 \x01(\x05H\x01R\bexitCode\x88\x01\x01B\v\n" +
	"\t_ended_atB\f\n" +
	"\n" +
	"_exit_code\"\xa4\x04\n" +
	"\rServerCommand\x12I\n" +
	"\x0ecreate_session\x18\x01 \x01(\v2 .claudeplane.v1.CreateSessionCmdH\x00R\rcreateSession\x12I\n" +
	"\x0eattach_session\x18\x02 \x01(\v2 .claudeplane.v1.AttachSessionCmdH\x00R\rattachSession\x12I\n" +
	"\x0edetach_session\x18\x03 \x01(\v2 .claudeplane.v1.DetachSessionCmdH\x00R\rdetachSession\x12C\n" +
	"\fkill_session\x18\x04 \x01(\v2\x1e.claudeplane.v1.KillSessionCmdH\x00R\vkillSession\x12L\n" +
	"\x0fresize_terminal\x18\x05 \x01(\v2!.claudeplane.v1.ResizeTerminalCmdH\x00R\x0eresizeTerminal\x12=\n" +
	"\n" +
	"input_data\x18\x06 \x01(\v2\x1c.claudeplane.v1.InputDataCmdH\x00R\tinputData\x12U\n" +
	"\x12request_scrollback\x18\a \x01(\v2$.claudeplane.v1.RequestScrollbackCmdH\x00R\x11requestScrollbackB\t\n" +
	"\acommand\"\xf0\x02\n" +
	"\x10CreateSessionCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12H\n" +
	"\benv_vars\x18\x03 \x03(\v2-.claudeplane.v1.CreateSessionCmd.EnvVarsEntryR\aenvVars\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12%\n" +
	"\x0einitial_prompt\x18\x06 \x01(\tR\rinitialPrompt\x12A\n" +
	"\rterminal_size\x18\a \x01(\v2\x1c.claudeplane.v1.TerminalSizeR\fterminalSize\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x10AttachSessionCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"1\n" +
	"\x10DetachSessionCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"G\n" +
	"\x0eKillSessionCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\"d\n" +
	"\x11ResizeTerminalCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\x04size\x18\x02 \x01(\v2\x1c.claudeplane.v1.TerminalSizeR\x04size\"A\n" +
	"\fInputDataCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"5\n" +
	"\x14RequestScrollbackCmd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\fTerminalSize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x80\x03\n" +
	"\n" +
	"AgentEvent\x12K\n" +
	"\x0esession_output\x18\x01 \x01(\v2\".claudeplane.v1.SessionOutputEventH\x00R\rsessionOutput\x12K\n" +
	"\x0esession_status\x18\x02 \x01(\v2\".claudeplane.v1.SessionStatusEventH\x00R\rsessionStatus\x125\n" +
	"\x06health\x18\x03 \x01(\v2\x1b.claudeplane.v1.HealthEventH\x00R\x06health\x12Q\n" +
	"\x10scrollback_chunk\x18\x04 \x01(\v2$.claudeplane.v1.ScrollbackChunkEventH\x00R\x0fscrollbackChunk\x12E\n" +
	"\fsession_exit\x18\x05 \x01(\v2 .claudeplane.v1.SessionExitEventH\x00R\vsessionExitB\a\n" +
	"\x05event\"e\n" +
	"\x12SessionOutputEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x01R\ttimestamp\"K\n" +
	"\x12SessionStatusEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xb2\x01\n" +
	"\x10SessionExitEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x127\n" +
	"\texited_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bexitedAt\x12)\n" +
	"\x10scrollback_bytes\x18\x04 \x01(\x03R\x0fscrollbackBytes\"\xd9\x01\n" +
	"\vHealthEvent\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x02R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x03R\x0fmemoryUsedBytes\x12&\n" +
	"\x0fdisk_free_bytes\x18\x03 \x01(\x03R\rdiskFreeBytes\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\x05R\x0eactiveSessions\x12!\n" +
	"\fmax_sessions\x18\x05 \x01(\x05R\vmaxSessions\"\x9d\x01\n" +
	"\x14ScrollbackChunkEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset2\xad\x01\n" +
	"\fAgentService\x12M\n" +
	"\bRegister\x12\x1f.claudeplane.v1.RegisterRequest\x1a .claudeplane.v1.RegisterResponse\x12N\n" +
	"\rCommandStream\x12\x1a.claudeplane.v1.AgentEvent\x1a\x1d.claudeplane.v1.ServerCommand(\x010\x01B\xd1\x01\n" +
	"\x12com.claudeplane.v1B\n" +
	"AgentProtoP\x01ZVgithub.com/claudeplane/claude-plane/internal/shared/proto/claudeplane/v1;claudeplanev1\xa2\x02\x03CXX\xaa\x02\x0eClaudeplane.V1\xca\x02\x0eClaudeplane\\V1\xe2\x02\x1aClaudeplane\\V1\\GPBMetadata\xea\x02\x0fClaudeplane::V1b\x06proto3"

var (
	file_claudeplane_v1_agent_proto_rawDescOnce sync.Once
	file_claudeplane_v1_agent_proto_rawDescData []byte
)

func file_claudeplane_v1_agent_proto_rawDescGZIP() []byte {
	file_claudeplane_v1_agent_proto_rawDescOnce.Do(func() {
		file_claudeplane_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_claudeplane_v1_agent_proto_rawDesc), len(file_claudeplane_v1_agent_proto_rawDesc)))
	})
	return file_claudeplane_v1_agent_proto_rawDescData
}

var file_claudeplane_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_claudeplane_v1_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: claudeplane.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: claudeplane.v1.RegisterResponse
	(*ResourceInfo)(nil),          // 2: claudeplane.v1.ResourceInfo
	(*SessionState)(nil),          // 3: claudeplane.v1.SessionState
	(*ServerCommand)(nil),         // 4: claudeplane.v1.ServerCommand
	(*CreateSessionCmd)(nil),      // 5: claudeplane.v1.CreateSessionCmd
	(*AttachSessionCmd)(nil),      // 6: claudeplane.v1.AttachSessionCmd
	(*DetachSessionCmd)(nil),      // 7: claudeplane.v1.DetachSessionCmd
	(*KillSessionCmd)(nil),        // 8: claudeplane.v1.KillSessionCmd
	(*ResizeTerminalCmd)(nil),     // 9: claudeplane.v1.ResizeTerminalCmd
	(*InputDataCmd)(nil),          // 10: claudeplane.v1.InputDataCmd
	(*RequestScrollbackCmd)(nil),  // 11: claudeplane.v1.RequestScrollbackCmd
	(*TerminalSize)(nil),          // 12: claudeplane.v1.TerminalSize
	(*AgentEvent)(nil),            // 13: claudeplane.v1.AgentEvent
	(*SessionOutputEvent)(nil),    // 14: claudeplane.v1.SessionOutputEvent
	(*SessionStatusEvent)(nil),    // 15: claudeplane.v1.SessionStatusEvent
	(*SessionExitEvent)(nil),      // 16: claudeplane.v1.SessionExitEvent
	(*HealthEvent)(nil),           // 17: claudeplane.v1.HealthEvent
	(*ScrollbackChunkEvent)(nil),  // 18: claudeplane.v1.ScrollbackChunkEvent
	nil,                           // 19: claudeplane.v1.CreateSessionCmd.EnvVarsEntry
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_claudeplane_v1_agent_proto_depIdxs = []int32{
	2,  // 0: claudeplane.v1.RegisterRequest.resources:type_name -> claudeplane.v1.ResourceInfo
	3,  // 1: claudeplane.v1.RegisterRequest.existing_sessions:type_name -> claudeplane.v1.SessionState
	20, // 2: claudeplane.v1.SessionState.started_at:type_name -> google.protobuf.Timestamp
	20, // 3: claudeplane.v1.SessionState.ended_at:type_name -> google.protobuf.Timestamp
	5,  // 4: claudeplane.v1.ServerCommand.create_session:type_name -> claudeplane.v1.CreateSessionCmd
	6,  // 5: claudeplane.v1.ServerCommand.attach_session:type_name -> claudeplane.v1.AttachSessionCmd
	7,  // 6: claudeplane.v1.ServerCommand.detach_session:type_name -> claudeplane.v1.DetachSessionCmd
	8,  // 7: claudeplane.v1.ServerCommand.kill_session:type_name -> claudeplane.v1.KillSessionCmd
	9,  // 8: claudeplane.v1.ServerCommand.resize_terminal:type_name -> claudeplane.v1.ResizeTerminalCmd
	10, // 9: claudeplane.v1.ServerCommand.input_data:type_name -> claudeplane.v1.InputDataCmd
	11, // 10: claudeplane.v1.ServerCommand.request_scrollback:type_name -> claudeplane.v1.RequestScrollbackCmd
	19, // 11: claudeplane.v1.CreateSessionCmd.env_vars:type_name -> claudeplane.v1.CreateSessionCmd.EnvVarsEntry
	12, // 12: claudeplane.v1.CreateSessionCmd.terminal_size:type_name -> claudeplane.v1.TerminalSize
	12, // 13: claudeplane.v1.ResizeTerminalCmd.size:type_name -> claudeplane.v1.TerminalSize
	14, // 14: claudeplane.v1.AgentEvent.session_output:type_name -> claudeplane.v1.SessionOutputEvent
	15, // 15: claudeplane.v1.AgentEvent.session_status:type_name -> claudeplane.v1.SessionStatusEvent
	17, // 16: claudeplane.v1.AgentEvent.health:type_name -> claudeplane.v1.HealthEvent
	18, // 17: claudeplane.v1.AgentEvent.scrollback_chunk:type_name -> claudeplane.v1.ScrollbackChunkEvent
	16, // 18: claudeplane.v1.AgentEvent.session_exit:type_name -> claudeplane.v1.SessionExitEvent
	20, // 19: claudeplane.v1.SessionExitEvent.exited_at:type_name -> google.protobuf.Timestamp
	0,  // 20: claudeplane.v1.AgentService.Register:input_type -> claudeplane.v1.RegisterRequest
	13, // 21: claudeplane.v1.AgentService.CommandStream:input_type -> claudeplane.v1.AgentEvent
	1,  // 22: claudeplane.v1.AgentService.Register:output_type -> claudeplane.v1.RegisterResponse
	4,  // 23: claudeplane.v1.AgentService.CommandStream:output_type -> claudeplane.v1.ServerCommand
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_claudeplane_v1_agent_proto_init() }
func file_claudeplane_v1_agent_proto_init() {
	if File_claudeplane_v1_agent_proto != nil {
		return
	}
	file_claudeplane_v1_agent_proto_msgTypes[3].OneofWrappers = []any{}
	file_claudeplane_v1_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerCommand_CreateSession)(nil),
		(*ServerCommand_AttachSession)(nil),
		(*ServerCommand_DetachSession)(nil),
		(*ServerCommand_KillSession)(nil),
		(*ServerCommand_ResizeTerminal)(nil),
		(*ServerCommand_InputData)(nil),
		(*ServerCommand_RequestScrollback)(nil),
	}
	file_claudeplane_v1_agent_proto_msgTypes[13].OneofWrappers = []any{
		(*AgentEvent_SessionOutput)(nil),
		(*AgentEvent_SessionStatus)(nil),
		(*AgentEvent_Health)(nil),
		(*AgentEvent_ScrollbackChunk)(nil),
		(*AgentEvent_SessionExit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_claudeplane_v1_agent_proto_rawDesc), len(file_claudeplane_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_claudeplane_v1_agent_proto_goTypes,
		DependencyIndexes: file_claudeplane_v1_agent_proto_depIdxs,
		MessageInfos:      file_claudeplane_v1_agent_proto_msgTypes,
	}.Build()
	File_claudeplane_v1_agent_proto = out.File
	file_claudeplane_v1_agent_proto_goTypes = nil
	file_claudeplane_v1_agent_proto_depIdxs = nil
}
